///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutoInstall
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutoInstallRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("41d3209a-6b55-4d11-ade5-8b107ab3f7a7")]
    public partial class AutoInstallRepository : RepoGenBaseFolder
    {
        static AutoInstallRepository instance = new AutoInstallRepository();
        AutoInstallRepositoryFolders.HeavyBidServerSetupAppFolder _heavybidserversetup;

        /// <summary>
        /// Gets the singleton class instance representing the AutoInstallRepository element repository.
        /// </summary>
        [RepositoryFolder("41d3209a-6b55-4d11-ade5-8b107ab3f7a7")]
        public static AutoInstallRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutoInstallRepository() 
            : base("AutoInstallRepository", "/", null, 0, false, "41d3209a-6b55-4d11-ade5-8b107ab3f7a7", ".\\RepositoryImages\\AutoInstallRepository41d3209a.rximgres")
        {
            _heavybidserversetup = new AutoInstallRepositoryFolders.HeavyBidServerSetupAppFolder(this);
        }

#region Variables

        string _InstallTypeButton = "Multi-user";

        /// <summary>
        /// Gets or sets the value of variable InstallTypeButton.
        /// </summary>
        [TestVariable("a3d965a8-d752-440b-b2de-047cd8f1fb64")]
        public string InstallTypeButton
        {
            get { return _InstallTypeButton; }
            set { _InstallTypeButton = value; }
        }

        string _HBInstallLocation = "C:\\HeavyBid\\";

        /// <summary>
        /// Gets or sets the value of variable HBInstallLocation.
        /// </summary>
        [TestVariable("80546008-1e14-4a93-9fa0-ad88d1afbcd1")]
        public string HBInstallLocation
        {
            get { return _HBInstallLocation; }
            set { _HBInstallLocation = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("41d3209a-6b55-4d11-ade5-8b107ab3f7a7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HeavyBidServerSetup folder.
        /// </summary>
        [RepositoryFolder("2e44eb69-e64f-4865-a068-d42ddcd932f4")]
        public virtual AutoInstallRepositoryFolders.HeavyBidServerSetupAppFolder HeavyBidServerSetup
        {
            get { return _heavybidserversetup; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class AutoInstallRepositoryFolders
    {
        /// <summary>
        /// The HeavyBidServerSetupAppFolder folder.
        /// </summary>
        [RepositoryFolder("2e44eb69-e64f-4865-a068-d42ddcd932f4")]
        public partial class HeavyBidServerSetupAppFolder : RepoGenBaseFolder
        {
            AutoInstallRepositoryFolders.ButtonsFolder _buttons;
            AutoInstallRepositoryFolders.TextContainersForValidationFolder _textcontainersforvalidation;
            AutoInstallRepositoryFolders.InstallTypesFolder _installtypes;
            RepoItemInfo _iacceptthetermsinthelicenseagreemInfo;

            /// <summary>
            /// Creates a new HeavyBidServerSetup  folder.
            /// </summary>
            public HeavyBidServerSetupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidServerSetup", "/form[@title~'HeavyBid' and @title~'Setup']", parentFolder, 30000, null, false, "2e44eb69-e64f-4865-a068-d42ddcd932f4", "")
            {
                _buttons = new AutoInstallRepositoryFolders.ButtonsFolder(this);
                _textcontainersforvalidation = new AutoInstallRepositoryFolders.TextContainersForValidationFolder(this);
                _installtypes = new AutoInstallRepositoryFolders.InstallTypesFolder(this);
                _iacceptthetermsinthelicenseagreemInfo = new RepoItemInfo(this, "IAcceptTheTermsInTheLicenseAgreem", "checkbox[@text~'terms']", 30000, null, "f13cd8b9-49c3-44c9-a77a-a4beb262908f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2e44eb69-e64f-4865-a068-d42ddcd932f4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2e44eb69-e64f-4865-a068-d42ddcd932f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item.
            /// </summary>
            [RepositoryItem("f13cd8b9-49c3-44c9-a77a-a4beb262908f")]
            public virtual Ranorex.CheckBox IAcceptTheTermsInTheLicenseAgreem
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item info.
            /// </summary>
            [RepositoryItemInfo("f13cd8b9-49c3-44c9-a77a-a4beb262908f")]
            public virtual RepoItemInfo IAcceptTheTermsInTheLicenseAgreemInfo
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo;
                }
            }

            /// <summary>
            /// The Buttons folder.
            /// </summary>
            [RepositoryFolder("4913e9c7-63d1-491f-89d6-367346999470")]
            public virtual AutoInstallRepositoryFolders.ButtonsFolder Buttons
            {
                get { return _buttons; }
            }

            /// <summary>
            /// The TextContainersForValidation folder.
            /// </summary>
            [RepositoryFolder("42b7d3a5-aa6b-46a5-8663-ff0f783fbd0d")]
            public virtual AutoInstallRepositoryFolders.TextContainersForValidationFolder TextContainersForValidation
            {
                get { return _textcontainersforvalidation; }
            }

            /// <summary>
            /// The InstallTypes folder.
            /// </summary>
            [RepositoryFolder("57f8a040-62c7-4885-974f-122dea3674d9")]
            public virtual AutoInstallRepositoryFolders.InstallTypesFolder InstallTypes
            {
                get { return _installtypes; }
            }
        }

        /// <summary>
        /// The ButtonsFolder folder.
        /// </summary>
        [RepositoryFolder("4913e9c7-63d1-491f-89d6-367346999470")]
        public partial class ButtonsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextbuttonInfo;
            RepoItemInfo _yesbuttonInfo;
            RepoItemInfo _installbuttonInfo;
            RepoItemInfo _finishbuttonInfo;

            /// <summary>
            /// Creates a new Buttons  folder.
            /// </summary>
            public ButtonsFolder(RepoGenBaseFolder parentFolder) :
                    base("Buttons", "", parentFolder, 0, null, false, "4913e9c7-63d1-491f-89d6-367346999470", "")
            {
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", "button[@text~'Next']", 30000, null, "fb614947-6e78-4d5d-9b27-bd5901e708a2");
                _yesbuttonInfo = new RepoItemInfo(this, "YesButton", "button[@text~'Yes']", 30000, null, "38d823d3-b7eb-40d7-9a74-af9c0b85e2f9");
                _installbuttonInfo = new RepoItemInfo(this, "InstallButton", "button[@text~'Install']", 30000, null, "01d7ca0c-7fe4-444e-b929-505e743554cf");
                _finishbuttonInfo = new RepoItemInfo(this, "FinishButton", "button[@text~'Finish']", 30000, null, "c2c3cc78-a171-4b8b-aec4-157c5a190939");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4913e9c7-63d1-491f-89d6-367346999470")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("fb614947-6e78-4d5d-9b27-bd5901e708a2")]
            public virtual Ranorex.Button NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("fb614947-6e78-4d5d-9b27-bd5901e708a2")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }

            /// <summary>
            /// The YesButton item.
            /// </summary>
            [RepositoryItem("38d823d3-b7eb-40d7-9a74-af9c0b85e2f9")]
            public virtual Ranorex.Button YesButton
            {
                get
                {
                    return _yesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YesButton item info.
            /// </summary>
            [RepositoryItemInfo("38d823d3-b7eb-40d7-9a74-af9c0b85e2f9")]
            public virtual RepoItemInfo YesButtonInfo
            {
                get
                {
                    return _yesbuttonInfo;
                }
            }

            /// <summary>
            /// The InstallButton item.
            /// </summary>
            [RepositoryItem("01d7ca0c-7fe4-444e-b929-505e743554cf")]
            public virtual Ranorex.Button InstallButton
            {
                get
                {
                    return _installbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The InstallButton item info.
            /// </summary>
            [RepositoryItemInfo("01d7ca0c-7fe4-444e-b929-505e743554cf")]
            public virtual RepoItemInfo InstallButtonInfo
            {
                get
                {
                    return _installbuttonInfo;
                }
            }

            /// <summary>
            /// The FinishButton item.
            /// </summary>
            [RepositoryItem("c2c3cc78-a171-4b8b-aec4-157c5a190939")]
            public virtual Ranorex.Button FinishButton
            {
                get
                {
                    return _finishbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FinishButton item info.
            /// </summary>
            [RepositoryItemInfo("c2c3cc78-a171-4b8b-aec4-157c5a190939")]
            public virtual RepoItemInfo FinishButtonInfo
            {
                get
                {
                    return _finishbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The TextContainersForValidationFolder folder.
        /// </summary>
        [RepositoryFolder("42b7d3a5-aa6b-46a5-8663-ff0f783fbd0d")]
        public partial class TextContainersForValidationFolder : RepoGenBaseFolder
        {
            AutoInstallRepositoryFolders.WelcomeScreenFolder _welcomescreen;
            AutoInstallRepositoryFolders.DestinationFolderScreenFolder _destinationfolderscreen;
            AutoInstallRepositoryFolders.PreviousInstallationScreenFolder _previousinstallationscreen;
            AutoInstallRepositoryFolders.ReadyToInstallScreenFolder _readytoinstallscreen;
            RepoItemInfo _titlebarInfo;

            /// <summary>
            /// Creates a new TextContainersForValidation  folder.
            /// </summary>
            public TextContainersForValidationFolder(RepoGenBaseFolder parentFolder) :
                    base("TextContainersForValidation", "", parentFolder, 0, null, false, "42b7d3a5-aa6b-46a5-8663-ff0f783fbd0d", "")
            {
                _welcomescreen = new AutoInstallRepositoryFolders.WelcomeScreenFolder(this);
                _destinationfolderscreen = new AutoInstallRepositoryFolders.DestinationFolderScreenFolder(this);
                _previousinstallationscreen = new AutoInstallRepositoryFolders.PreviousInstallationScreenFolder(this);
                _readytoinstallscreen = new AutoInstallRepositoryFolders.ReadyToInstallScreenFolder(this);
                _titlebarInfo = new RepoItemInfo(this, "Titlebar", "titlebar", 30000, null, "dddd424d-c9ea-451b-9ae6-d11ef58210a7");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("42b7d3a5-aa6b-46a5-8663-ff0f783fbd0d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Titlebar item.
            /// </summary>
            [RepositoryItem("dddd424d-c9ea-451b-9ae6-d11ef58210a7")]
            public virtual Ranorex.TitleBar Titlebar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The Titlebar item info.
            /// </summary>
            [RepositoryItemInfo("dddd424d-c9ea-451b-9ae6-d11ef58210a7")]
            public virtual RepoItemInfo TitlebarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The WelcomeScreen folder.
            /// </summary>
            [RepositoryFolder("7a6f96ba-6458-49cc-8b33-a8509ad9fec1")]
            public virtual AutoInstallRepositoryFolders.WelcomeScreenFolder WelcomeScreen
            {
                get { return _welcomescreen; }
            }

            /// <summary>
            /// The DestinationFolderScreen folder.
            /// </summary>
            [RepositoryFolder("2065c0cf-cd78-4b5a-8b3c-c33f032c48c4")]
            public virtual AutoInstallRepositoryFolders.DestinationFolderScreenFolder DestinationFolderScreen
            {
                get { return _destinationfolderscreen; }
            }

            /// <summary>
            /// The PreviousInstallationScreen folder.
            /// </summary>
            [RepositoryFolder("fffe4246-75c6-4623-8543-6244d5c60e6e")]
            public virtual AutoInstallRepositoryFolders.PreviousInstallationScreenFolder PreviousInstallationScreen
            {
                get { return _previousinstallationscreen; }
            }

            /// <summary>
            /// The ReadyToInstallScreen folder.
            /// </summary>
            [RepositoryFolder("5e55edea-55ee-4cb2-8c6f-8f54356b07a7")]
            public virtual AutoInstallRepositoryFolders.ReadyToInstallScreenFolder ReadyToInstallScreen
            {
                get { return _readytoinstallscreen; }
            }
        }

        /// <summary>
        /// The WelcomeScreenFolder folder.
        /// </summary>
        [RepositoryFolder("7a6f96ba-6458-49cc-8b33-a8509ad9fec1")]
        public partial class WelcomeScreenFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titletextInfo;
            RepoItemInfo _maintextInfo;

            /// <summary>
            /// Creates a new WelcomeScreen  folder.
            /// </summary>
            public WelcomeScreenFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeScreen", "", parentFolder, 0, null, false, "7a6f96ba-6458-49cc-8b33-a8509ad9fec1", "")
            {
                _titletextInfo = new RepoItemInfo(this, "TitleText", "text[@accessiblerole~'StaticText'][2]", 30000, null, "9fe9891e-ebc9-425c-a6db-f64dbacb3e93");
                _maintextInfo = new RepoItemInfo(this, "MainText", "text[@accessiblerole~'StaticText'][1]", 30000, null, "65f21614-c071-4cfe-a2e6-4dcd56d23514");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7a6f96ba-6458-49cc-8b33-a8509ad9fec1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleText item.
            /// </summary>
            [RepositoryItem("9fe9891e-ebc9-425c-a6db-f64dbacb3e93")]
            public virtual Ranorex.Text TitleText
            {
                get
                {
                    return _titletextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TitleText item info.
            /// </summary>
            [RepositoryItemInfo("9fe9891e-ebc9-425c-a6db-f64dbacb3e93")]
            public virtual RepoItemInfo TitleTextInfo
            {
                get
                {
                    return _titletextInfo;
                }
            }

            /// <summary>
            /// The MainText item.
            /// </summary>
            [RepositoryItem("65f21614-c071-4cfe-a2e6-4dcd56d23514")]
            public virtual Ranorex.Text MainText
            {
                get
                {
                    return _maintextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MainText item info.
            /// </summary>
            [RepositoryItemInfo("65f21614-c071-4cfe-a2e6-4dcd56d23514")]
            public virtual RepoItemInfo MainTextInfo
            {
                get
                {
                    return _maintextInfo;
                }
            }
        }

        /// <summary>
        /// The DestinationFolderScreenFolder folder.
        /// </summary>
        [RepositoryFolder("2065c0cf-cd78-4b5a-8b3c-c33f032c48c4")]
        public partial class DestinationFolderScreenFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filepathtextboxInfo;

            /// <summary>
            /// Creates a new DestinationFolderScreen  folder.
            /// </summary>
            public DestinationFolderScreenFolder(RepoGenBaseFolder parentFolder) :
                    base("DestinationFolderScreen", "", parentFolder, 0, null, false, "2065c0cf-cd78-4b5a-8b3c-c33f032c48c4", "")
            {
                _filepathtextboxInfo = new RepoItemInfo(this, "FilepathTextbox", "text[@accessiblerole='Text']", 30000, null, "e282ea00-d192-448e-bce4-10c58d4d949b");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2065c0cf-cd78-4b5a-8b3c-c33f032c48c4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilepathTextbox item.
            /// </summary>
            [RepositoryItem("e282ea00-d192-448e-bce4-10c58d4d949b")]
            public virtual Ranorex.Text FilepathTextbox
            {
                get
                {
                    return _filepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilepathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("e282ea00-d192-448e-bce4-10c58d4d949b")]
            public virtual RepoItemInfo FilepathTextboxInfo
            {
                get
                {
                    return _filepathtextboxInfo;
                }
            }
        }

        /// <summary>
        /// The PreviousInstallationScreenFolder folder.
        /// </summary>
        [RepositoryFolder("fffe4246-75c6-4623-8543-6244d5c60e6e")]
        public partial class PreviousInstallationScreenFolder : RepoGenBaseFolder
        {
            RepoItemInfo _previousinstallpopupInfo;

            /// <summary>
            /// Creates a new PreviousInstallationScreen  folder.
            /// </summary>
            public PreviousInstallationScreenFolder(RepoGenBaseFolder parentFolder) :
                    base("PreviousInstallationScreen", "", parentFolder, 0, null, false, "fffe4246-75c6-4623-8543-6244d5c60e6e", "")
            {
                _previousinstallpopupInfo = new RepoItemInfo(this, "PreviousInstallPopup", "text[@text~'previous' or @text~'overwritten']", 30000, null, "dd318b6d-5722-449b-abd0-b15bc9e4729a");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fffe4246-75c6-4623-8543-6244d5c60e6e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PreviousInstallPopup item.
            /// </summary>
            [RepositoryItem("dd318b6d-5722-449b-abd0-b15bc9e4729a")]
            public virtual Ranorex.Text PreviousInstallPopup
            {
                get
                {
                    return _previousinstallpopupInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PreviousInstallPopup item info.
            /// </summary>
            [RepositoryItemInfo("dd318b6d-5722-449b-abd0-b15bc9e4729a")]
            public virtual RepoItemInfo PreviousInstallPopupInfo
            {
                get
                {
                    return _previousinstallpopupInfo;
                }
            }
        }

        /// <summary>
        /// The ReadyToInstallScreenFolder folder.
        /// </summary>
        [RepositoryFolder("5e55edea-55ee-4cb2-8c6f-8f54356b07a7")]
        public partial class ReadyToInstallScreenFolder : RepoGenBaseFolder
        {
            RepoItemInfo _confirmfilepathtextboxInfo;

            /// <summary>
            /// Creates a new ReadyToInstallScreen  folder.
            /// </summary>
            public ReadyToInstallScreenFolder(RepoGenBaseFolder parentFolder) :
                    base("ReadyToInstallScreen", "", parentFolder, 0, null, false, "5e55edea-55ee-4cb2-8c6f-8f54356b07a7", "")
            {
                _confirmfilepathtextboxInfo = new RepoItemInfo(this, "ConfirmFilepathTextbox", "text[@text~'install HeavyBid in:']", 30000, null, "1f669d2f-0060-46e6-b72d-dff298a045e0");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e55edea-55ee-4cb2-8c6f-8f54356b07a7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ConfirmFilepathTextbox item.
            /// </summary>
            [RepositoryItem("1f669d2f-0060-46e6-b72d-dff298a045e0")]
            public virtual Ranorex.Text ConfirmFilepathTextbox
            {
                get
                {
                    return _confirmfilepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ConfirmFilepathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("1f669d2f-0060-46e6-b72d-dff298a045e0")]
            public virtual RepoItemInfo ConfirmFilepathTextboxInfo
            {
                get
                {
                    return _confirmfilepathtextboxInfo;
                }
            }
        }

        /// <summary>
        /// The InstallTypesFolder folder.
        /// </summary>
        [RepositoryFolder("57f8a040-62c7-4885-974f-122dea3674d9")]
        public partial class InstallTypesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _multiusermultipleuserscanworkintInfo;
            RepoItemInfo _standaloneinstalltypeInfo;
            RepoItemInfo _traininginstalltypeInfo;

            /// <summary>
            /// Creates a new InstallTypes  folder.
            /// </summary>
            public InstallTypesFolder(RepoGenBaseFolder parentFolder) :
                    base("InstallTypes", "", parentFolder, 0, null, false, "57f8a040-62c7-4885-974f-122dea3674d9", "")
            {
                _multiusermultipleuserscanworkintInfo = new RepoItemInfo(this, "MultiUserMultipleUsersCanWorkInT", "?/?/radiobutton[@text~'Multi-user']", 30000, null, "87f3d72a-a7d3-4b0f-9b41-5932103d923d");
                _standaloneinstalltypeInfo = new RepoItemInfo(this, "StandaloneInstallType", "?/?/radiobutton[@text~'Standalone']", 30000, null, "3ca18573-3cd1-442a-82aa-f72fbe2a0b91");
                _traininginstalltypeInfo = new RepoItemInfo(this, "TrainingInstallType", "?/?/radiobutton[@text~'Training']", 30000, null, "aa762aff-1fe2-4006-acb0-afc3774cf5dd");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("57f8a040-62c7-4885-974f-122dea3674d9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MultiUserMultipleUsersCanWorkInT item.
            /// </summary>
            [RepositoryItem("87f3d72a-a7d3-4b0f-9b41-5932103d923d")]
            public virtual Ranorex.RadioButton MultiUserMultipleUsersCanWorkInT
            {
                get
                {
                    return _multiusermultipleuserscanworkintInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MultiUserMultipleUsersCanWorkInT item info.
            /// </summary>
            [RepositoryItemInfo("87f3d72a-a7d3-4b0f-9b41-5932103d923d")]
            public virtual RepoItemInfo MultiUserMultipleUsersCanWorkInTInfo
            {
                get
                {
                    return _multiusermultipleuserscanworkintInfo;
                }
            }

            /// <summary>
            /// The StandaloneInstallType item.
            /// </summary>
            [RepositoryItem("3ca18573-3cd1-442a-82aa-f72fbe2a0b91")]
            public virtual Ranorex.RadioButton StandaloneInstallType
            {
                get
                {
                    return _standaloneinstalltypeInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The StandaloneInstallType item info.
            /// </summary>
            [RepositoryItemInfo("3ca18573-3cd1-442a-82aa-f72fbe2a0b91")]
            public virtual RepoItemInfo StandaloneInstallTypeInfo
            {
                get
                {
                    return _standaloneinstalltypeInfo;
                }
            }

            /// <summary>
            /// The TrainingInstallType item.
            /// </summary>
            [RepositoryItem("aa762aff-1fe2-4006-acb0-afc3774cf5dd")]
            public virtual Ranorex.RadioButton TrainingInstallType
            {
                get
                {
                    return _traininginstalltypeInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The TrainingInstallType item info.
            /// </summary>
            [RepositoryItemInfo("aa762aff-1fe2-4006-acb0-afc3774cf5dd")]
            public virtual RepoItemInfo TrainingInstallTypeInfo
            {
                get
                {
                    return _traininginstalltypeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}