///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;


using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutoInstall
{
    public partial class Compare17Folders
    {
       		string dir = @"Downloads\InternFinal\InternFinal\Script\Reports\";
       		string refDir = @"W:\HBDaily\InstallAutomation\Script\Reports\Reference\";
            string binDiff = @"binDiff.txt";
            string hcssDiff = @"hcssDiff.txt";
            string sysDiff = @"sysDiff.txt";
            string utilDiff = @"DiffUTIL.txt";
            
            
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ValidateDiffFrom17()
        {
            string pathBin = Path.Combine(dir,binDiff);
            string pathSys = Path.Combine(dir,hcssDiff);
            string pathUtil = Path.Combine(dir,sysDiff);
            string pathHcss = Path.Combine(dir,utilDiff);
            
      		if (File.Exists(pathBin))
			   {
        		Report.Success("File Exist", "Success! " + binDiff + " exists!");
			   }
			else                  
			   {
				Report.Failure("File Exist", "Fail. " + binDiff + " does not exists.");
			   }
			
			if (File.Exists(pathSys))
			   {
        		Report.Success("File Exist", "Success! " + hcssDiff + " exists!");
			   }
			else                  
			   {
				Report.Failure("File Exist", "Fail. " + hcssDiff + " does not exists.");
			   }
			
			if (File.Exists(pathUtil))
			   {
        		Report.Success("File Exist", "Success! " + sysDiff + " exists!");
			   }
			else                  
			   {
				Report.Failure("File Exist", "Fail. " + sysDiff + " does not exists.");
			   }
			
			if (File.Exists(pathHcss))
			   {
        		Report.Success("File Exist", "Success! " + utilDiff + " exists!");
			   }
			else                  
			   {
				Report.Failure("File Exist", "Fail. " + utilDiff + " does not exists.");
			   }
			
        }

        public void ValidateUTILReportContent()
        {
        		string filePath_Expected = Path.Combine(dir,utilDiff);
				string filePath_Current = Path.Combine(refDir,utilDiff);
				
			    string customLogMessage = string.Empty;	
			               // prepare log messages  
			    const string fileNotFoundMessage = "File not found for comparison in Validate_FileContentEqual: {0}";  
			    const string logMessage = "Comparing content of files ({0} vs. {1})";  
			    if (string.IsNullOrEmpty(customLogMessage))  
			    {  
			        customLogMessage = string.Format(logMessage, filePath_Expected, filePath_Current);  
			    }  
			  
			    // check if file exists  
			    if (!System.IO.File.Exists(filePath_Current))  
			    {  
			        throw new Ranorex.RanorexException(string.Format(fileNotFoundMessage, filePath_Current));  
			    }  
			  
			    // check if referencing file exists  
			    if (!System.IO.File.Exists(filePath_Expected))  
			    {  
			        throw new Ranorex.RanorexException(string.Format(fileNotFoundMessage, filePath_Expected));  
			    }  
			  
			    // check if filenames are identical  
			    if (filePath_Expected.Equals(filePath_Current))  
			    {  
			        Ranorex.Validate.IsTrue(true, customLogMessage);  
			    }  
			    else  
			    {  
			        string current = System.IO.File.ReadAllText(filePath_Current);  
			        string expected = System.IO.File.ReadAllText(filePath_Expected);  
			        // validate whether expected value equals to current value  
			        Ranorex.Validate.AreEqual(current, expected, customLogMessage);  
			    }  
        }

        public void ValidateBINReportContent()
        {
            string filePath_Expected = Path.Combine(dir,binDiff);
				string filePath_Current = Path.Combine(refDir,binDiff);
				
			    string customLogMessage = string.Empty;	
			               // prepare log messages  
			    const string fileNotFoundMessage = "File not found for comparison in Validate_FileContentEqual: {0}";  
			    const string logMessage = "Comparing content of files ({0} vs. {1})";  
			    if (string.IsNullOrEmpty(customLogMessage))  
			    {  
			        customLogMessage = string.Format(logMessage, filePath_Expected, filePath_Current);  
			    }  
			  
			    // check if file exists  
			    if (!System.IO.File.Exists(filePath_Current))  
			    {  
			        throw new Ranorex.RanorexException(string.Format(fileNotFoundMessage, filePath_Current));  
			    }  
			  
			    // check if referencing file exists  
			    if (!System.IO.File.Exists(filePath_Expected))  
			    {  
			        throw new Ranorex.RanorexException(string.Format(fileNotFoundMessage, filePath_Expected));  
			    }  
			  
			    // check if filenames are identical  
			    if (filePath_Expected.Equals(filePath_Current))  
			    {  
			        Ranorex.Validate.IsTrue(true, customLogMessage);  
			    }  
			    else  
			    {  
			        string current = System.IO.File.ReadAllText(filePath_Current);  
			        string expected = System.IO.File.ReadAllText(filePath_Expected);  
			        // validate whether expected value equals to current value  
			        Ranorex.Validate.AreEqual(current, expected, customLogMessage);  
			    }  
        }

        public void ValidateSYSReportContent()
        {
            string filePath_Expected = Path.Combine(dir,sysDiff);
				string filePath_Current = Path.Combine(refDir,sysDiff);
				
			    string customLogMessage = string.Empty;	
			               // prepare log messages  
			    const string fileNotFoundMessage = "File not found for comparison in Validate_FileContentEqual: {0}";  
			    const string logMessage = "Comparing content of files ({0} vs. {1})";  
			    if (string.IsNullOrEmpty(customLogMessage))  
			    {  
			        customLogMessage = string.Format(logMessage, filePath_Expected, filePath_Current);  
			    }  
			  
			    // check if file exists  
			    if (!System.IO.File.Exists(filePath_Current))  
			    {  
			        throw new Ranorex.RanorexException(string.Format(fileNotFoundMessage, filePath_Current));  
			    }  
			  
			    // check if referencing file exists  
			    if (!System.IO.File.Exists(filePath_Expected))  
			    {  
			        throw new Ranorex.RanorexException(string.Format(fileNotFoundMessage, filePath_Expected));  
			    }  
			  
			    // check if filenames are identical  
			    if (filePath_Expected.Equals(filePath_Current))  
			    {  
			        Ranorex.Validate.IsTrue(true, customLogMessage);  
			    }  
			    else  
			    {  
			        string current = System.IO.File.ReadAllText(filePath_Current);  
			        string expected = System.IO.File.ReadAllText(filePath_Expected);  
			        // validate whether expected value equals to current value  
			        Ranorex.Validate.AreEqual(current, expected, customLogMessage);  
			    }  
        }

        public void ValidateHCSSReportContent()
        {
            	string filePath_Expected = Path.Combine(dir,hcssDiff);
				string filePath_Current = Path.Combine(refDir,hcssDiff);
				
			    string customLogMessage = string.Empty;	
			               // prepare log messages  
			    const string fileNotFoundMessage = "File not found for comparison in Validate_FileContentEqual: {0}";  
			    const string logMessage = "Comparing content of files ({0} vs. {1})";  
			    if (string.IsNullOrEmpty(customLogMessage))  
			    {  
			        customLogMessage = string.Format(logMessage, filePath_Expected, filePath_Current);  
			    }  
			  
			    // check if file exists  
			    if (!System.IO.File.Exists(filePath_Current))  
			    {  
			        throw new Ranorex.RanorexException(string.Format(fileNotFoundMessage, filePath_Current));  
			    }  
			  
			    // check if referencing file exists  
			    if (!System.IO.File.Exists(filePath_Expected))  
			    {  
			        throw new Ranorex.RanorexException(string.Format(fileNotFoundMessage, filePath_Expected));  
			    }  
			  
			    // check if filenames are identical  
			    if (filePath_Expected.Equals(filePath_Current))  
			    {  
			        Ranorex.Validate.IsTrue(true, customLogMessage);  
			    }  
			    else  
			    {  
			        string current = System.IO.File.ReadAllText(filePath_Current);  
			        string expected = System.IO.File.ReadAllText(filePath_Expected);  
			        // validate whether expected value equals to current value  
			        Ranorex.Validate.AreEqual(current, expected, customLogMessage);  
			    }  
        }

    }
}
