///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;


using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutoInstall
{
    public partial class Compare17Folders
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ValidateDiffFrom17()
        {
            string dir = @"V:\alex.kwie\Script\Reports\";
            string binDiff = @"binDiff.txt";
            string hcssDiff = @"hcssDiff.txt";
            string sysDiff = @"sysDiff.txt";
            string utilDiff = @"utilDiff.txt";
            string pathBin = Path.Combine(dir,binDiff);
            string pathSys = Path.Combine(dir,hcssDiff);
            string pathUtil = Path.Combine(dir,sysDiff);
            string pathHcss = Path.Combine(dir,utilDiff);
            
      		if (File.Exists(pathBin))
			   {
        		Report.Success("File Exist", "Success! " + binDiff + " exists!");
			   }
			else                  
			   {
				Report.Failure("File Exist", "Fail. " + binDiff + " does not exists.");
			   }
			
			if (File.Exists(pathSys))
			   {
        		Report.Success("File Exist", "Success! " + hcssDiff + " exists!");
			   }
			else                  
			   {
				Report.Failure("File Exist", "Fail. " + hcssDiff + " does not exists.");
			   }
			
			if (File.Exists(pathUtil))
			   {
        		Report.Success("File Exist", "Success! " + sysDiff + " exists!");
			   }
			else                  
			   {
				Report.Failure("File Exist", "Fail. " + sysDiff + " does not exists.");
			   }
			
			if (File.Exists(pathHcss))
			   {
        		Report.Success("File Exist", "Success! " + utilDiff + " exists!");
			   }
			else                  
			   {
				Report.Failure("File Exist", "Fail. " + utilDiff + " does not exists.");
			   }
			
        }

    }
}
