///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutoInstall
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CustomBidProposalReport recording.
    /// </summary>
    [TestModule("192ecfb1-f9cd-4c22-8a6b-79d148535b72", ModuleType.Recording, 1)]
    public partial class CustomBidProposalReport : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutoInstallRepository repository.
        /// </summary>
        public static AutoInstallRepository repo = AutoInstallRepository.Instance;

        static CustomBidProposalReport instance = new CustomBidProposalReport();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CustomBidProposalReport()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CustomBidProposalReport Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Tabs.SummaryTab' at Center.", repo.HeavyBidApp.Tabs.SummaryTabInfo, new RecordItemIndex(0));
            repo.HeavyBidApp.Tabs.SummaryTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Buttons.Summary.CustomizedReportsButton' at Center.", repo.HeavyBidApp.Buttons.Summary.CustomizedReportsButtonInfo, new RecordItemIndex(1));
            repo.HeavyBidApp.Buttons.Summary.CustomizedReportsButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopUpScreens.FromSummaryButtons.CustomizedBidProposalSetup.PreviewReportButton' at Center.", repo.HBPopUpScreens.FromSummaryButtons.CustomizedBidProposalSetup.PreviewReportButtonInfo, new RecordItemIndex(2));
            repo.HBPopUpScreens.FromSummaryButtons.CustomizedBidProposalSetup.PreviewReportButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'HBReportViewers.CustomizedBidProposal'.", repo.HBReportViewers.CustomizedBidProposal.SelfInfo, new RecordItemIndex(3));
            Validate.Exists(repo.HBReportViewers.CustomizedBidProposal.SelfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBReportViewers.CustomizedBidProposal.ExportReportButton' at Center.", repo.HBReportViewers.CustomizedBidProposal.ExportReportButtonInfo, new RecordItemIndex(4));
            repo.HBReportViewers.CustomizedBidProposal.ExportReportButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBReportViewers.ExportScreen.FirstComboBox' at Center.", repo.HBReportViewers.ExportScreen.FirstComboBoxInfo, new RecordItemIndex(5));
            repo.HBReportViewers.ExportScreen.FirstComboBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBReportViewers.ListFormatExports.TXTFormat' at Center.", repo.HBReportViewers.ListFormatExports.TXTFormatInfo, new RecordItemIndex(6));
            repo.HBReportViewers.ListFormatExports.TXTFormat.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBReportViewers.ExportScreen.OKButton' at Center.", repo.HBReportViewers.ExportScreen.OKButtonInfo, new RecordItemIndex(7));
            repo.HBReportViewers.ExportScreen.OKButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBReportViewers.ChooseExportFileSaveDialog.FilePathURL' at CenterRight.", repo.HBReportViewers.ChooseExportFileSaveDialog.FilePathURLInfo, new RecordItemIndex(8));
            repo.HBReportViewers.ChooseExportFileSaveDialog.FilePathURL.Click(Location.CenterRight);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'x'.", new RecordItemIndex(9));
            Keyboard.Press("x");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBReportViewers.ChooseExportFileSaveDialog.FileName' at Center.", repo.HBReportViewers.ChooseExportFileSaveDialog.FileNameInfo, new RecordItemIndex(10));
            repo.HBReportViewers.ChooseExportFileSaveDialog.FileName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CustomizedBidProposal.txt'.", new RecordItemIndex(11));
            Keyboard.Press("CustomizedBidProposal.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBReportViewers.ChooseExportFileSaveDialog.SaveButton' at Center.", repo.HBReportViewers.ChooseExportFileSaveDialog.SaveButtonInfo, new RecordItemIndex(12));
            repo.HBReportViewers.ChooseExportFileSaveDialog.SaveButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(13));
            Delay.Duration(10000, false);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'HBReportViewers.FileAlreadyExists.YesButton' at Center.", repo.HBReportViewers.FileAlreadyExists.YesButtonInfo, new RecordItemIndex(14));
                repo.HBReportViewers.FileAlreadyExists.YesButton.Click();
                Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(14)); }
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'HBReportViewers.CustomizedBidProposal'.", repo.HBReportViewers.CustomizedBidProposal.SelfInfo, new RecordItemIndex(15));
            Host.Current.CloseApplication(repo.HBReportViewers.CustomizedBidProposal.Self, new Duration(0));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopUpScreens.FromSummaryButtons.CustomizedBidProposalSetup.CancelButton' at Center.", repo.HBPopUpScreens.FromSummaryButtons.CustomizedBidProposalSetup.CancelButtonInfo, new RecordItemIndex(16));
            repo.HBPopUpScreens.FromSummaryButtons.CustomizedBidProposalSetup.CancelButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
