///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutoInstall
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ExportToHeavyJob recording.
    /// </summary>
    [TestModule("543f4fdc-ef55-444d-b40a-1525e1788e4d", ModuleType.Recording, 1)]
    public partial class ExportToHeavyJob : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutoInstallRepository repository.
        /// </summary>
        public static AutoInstallRepository repo = AutoInstallRepository.Instance;

        static ExportToHeavyJob instance = new ExportToHeavyJob();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ExportToHeavyJob()
        {
            HJFilepath = "C:\\HeavyBidWS\\HBSave\\HeavyJobExport.xml";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ExportToHeavyJob Instance
        {
            get { return instance; }
        }

#region Variables

        string _HJFilepath;

        /// <summary>
        /// Gets or sets the value of variable HJFilepath.
        /// </summary>
        [TestVariable("a786da45-a0e9-42a0-b52e-a0ef780d039c")]
        public string HJFilepath
        {
            get { return _HJFilepath; }
            set { _HJFilepath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Tabs.ExchangeTab' at Center.", repo.HeavyBidApp.Tabs.ExchangeTabInfo, new RecordItemIndex(0));
            repo.HeavyBidApp.Tabs.ExchangeTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Buttons.Exchange.HJAndAccountingExport' at Center.", repo.HeavyBidApp.Buttons.Exchange.HJAndAccountingExportInfo, new RecordItemIndex(1));
            repo.HeavyBidApp.Buttons.Exchange.HJAndAccountingExport.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.DocumentInterface.Buttons.ExportToHeavyJobButton' at Center.", repo.HeavyBidApp.DocumentInterface.Buttons.ExportToHeavyJobButtonInfo, new RecordItemIndex(2));
            repo.HeavyBidApp.DocumentInterface.Buttons.ExportToHeavyJobButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$HJFilepath' with focus on 'HeavyBidApp.DocumentInterface.FilenameTextboxExportHJ'.", repo.HeavyBidApp.DocumentInterface.FilenameTextboxExportHJInfo, new RecordItemIndex(3));
            repo.HeavyBidApp.DocumentInterface.FilenameTextboxExportHJ.PressKeys(HJFilepath);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'HeavyBidApp.DocumentInterface.Buttons.ExportButton' at Center.", repo.HeavyBidApp.DocumentInterface.Buttons.ExportButtonInfo, new RecordItemIndex(4));
            repo.HeavyBidApp.DocumentInterface.Buttons.ExportButton.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeRegex (Text~'(C|c)omplete') on item 'HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.MainTextPopup'.", repo.HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.MainTextPopupInfo, new RecordItemIndex(5));
            Validate.AttributeRegex(repo.HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.MainTextPopupInfo, "Text", new Regex("(C|c)omplete"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.OKButton' at Center.", repo.HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.OKButtonInfo, new RecordItemIndex(6));
            repo.HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.OKButton.DoubleClick();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeRegex (Text~'(C|c)omplete') on item 'HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.MainTextPopup'.", repo.HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.MainTextPopupInfo, new RecordItemIndex(7));
                Validate.AttributeRegex(repo.HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.MainTextPopupInfo, "Text", new Regex("(C|c)omplete"), null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left DoubleClick item 'HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.OKButton' at Center.", repo.HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.OKButtonInfo, new RecordItemIndex(8));
                repo.HBPopUpScreens.FromExchangeButtons.ExportToHeavyJob.OKButton.DoubleClick();
                Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
