///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;


using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutoInstall
{
    public partial class ValidateCustomReport
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        /// 
        string dir = @"W:\HBDaily\InstallAutomation\HBReportsExportFiles\";
        string refDir = @"W:\HBDaily\InstallAutomation\HBReportsExportFiles\Reference";
        string file = @"CostReportClassic.txt";
          
        
        
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ValidateCustomerReport()
        {
          
        
        }
   

      

        public void ValidateContentCustomReport()
        {
            // TODO: Replace the following line with your code implementation.
            throw new NotImplementedException();
        }   
		    
		    
		    
        

    }
}
