///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutoInstall
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateBiditemStructureOutput recording.
    /// </summary>
    [TestModule("fa6d448f-fdd3-414f-92fb-9ce1b8f8ecbb", ModuleType.Recording, 1)]
    public partial class ValidateBiditemStructureOutput : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutoInstallRepository repository.
        /// </summary>
        public static AutoInstallRepository repo = AutoInstallRepository.Instance;

        static ValidateBiditemStructureOutput instance = new ValidateBiditemStructureOutput();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateBiditemStructureOutput()
        {
            RunLocation = "Downloads\\InternFinal\\InternFinal\\Script";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateBiditemStructureOutput Instance
        {
            get { return instance; }
        }

#region Variables

        string _RunLocation;

        /// <summary>
        /// Gets or sets the value of variable RunLocation.
        /// </summary>
        [TestVariable("40ef4384-ba8d-4ef9-b24d-710cdf23084c")]
        public string RunLocation
        {
            get { return _RunLocation; }
            set { _RunLocation = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'runBiditemStructure.bat' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("runBiditemStructure.bat", "", RunLocation, false);
            Delay.Milliseconds(0);
            
            BiditemStructureExists();
            Delay.Milliseconds(0);
            
            ValidateContentBiditemStructure();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
