///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.IO;
using System.Xml;
using System.Linq;
using System.Xml.Linq;
using System.Xml.XPath;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutoInstall
{
    public partial class ValidateHBStrayDate
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CheckStrayDate()
        {
        	
        	string stray = @"C:\HeavyBid\BIN\STRAY.XML";			//set pathfile to stray as variable
    	//  	string nodeName = "HeavyBid-Stray-Files";				//set name of desired element
    //	   	string rev = "revision";
//	string mod = "modified";
        	
        	XmlDocument Doc = new XmlDocument();

   			Doc.Load(stray);

		    XmlNodeList itemList = Doc.DocumentElement.SelectNodes("HeavyBid-Stray-Files");
    		foreach (XmlNode currNode in itemList)

		    {
		      string revision = string.Empty;  
		      revision = currNode.Attributes["Revision"].Value.ToString(); 
		        
		      Report.Success("xml", revision);
		      
		      
		    }
			
        }

    }
    
}