///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutoInstall
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateWSStrayDate recording.
    /// </summary>
    [TestModule("5cd0caf7-f833-4d29-aad4-fdd09da5c405", ModuleType.Recording, 1)]
    public partial class ValidateWSStrayDate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutoInstallRepository repository.
        /// </summary>
        public static AutoInstallRepository repo = AutoInstallRepository.Instance;

        static ValidateWSStrayDate instance = new ValidateWSStrayDate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateWSStrayDate()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateWSStrayDate Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'Excel.EXE' with arguments 'C:\\HeavyBidWS\\BIN\\STRAY.XML' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("Excel.EXE", "C:\\HeavyBidWS\\BIN\\STRAY.XML", "C:\\Program Files (x86)\\Microsoft Office", false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OpenXML.xmlTable' at Center.", repo.OpenXML.xmlTableInfo, new RecordItemIndex(1));
            repo.OpenXML.xmlTable.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OpenXML.OKButton' at Center.", repo.OpenXML.OKButtonInfo, new RecordItemIndex(2));
            repo.OpenXML.OKButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExcelXMLPopup.OKButton' at Center.", repo.ExcelXMLPopup.OKButtonInfo, new RecordItemIndex(3));
            repo.ExcelXMLPopup.OKButton.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'OfficeActivationSuite.CancelButton' at Center.", repo.OfficeActivationSuite.CancelButtonInfo, new RecordItemIndex(4));
                repo.OfficeActivationSuite.CancelButton.Click();
                Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2018') on item 'Excel.CellA2'.", repo.Excel.CellA2Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.Excel.CellA2Info, "Text", "2018");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='08/08/2017') on item 'Excel.CellB2'.", repo.Excel.CellB2Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.Excel.CellB2Info, "Text", "08/08/2017");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'Excel'.", repo.Excel.SelfInfo, new RecordItemIndex(7));
            Host.Current.CloseApplication(repo.Excel.Self, new Duration(0));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExcelXMLPopup.DontSaveButton' at Center.", repo.ExcelXMLPopup.DontSaveButtonInfo, new RecordItemIndex(8));
            repo.ExcelXMLPopup.DontSaveButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
