PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& 'V:\alex.kwie\Script\wsComparison.ps1'"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& 'V:\alex.kwie\Script\oldExeWS'"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& 'V:\alex.kwie\Script\oldExeServer.ps1'"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& 'V:\alex.kwie\Script\diff17util.ps1'"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& 'V:\alex.kwie\Script\diff17sys.ps1'"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& 'V:\alex.kwie\Script\diff17hcss.ps1'"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& 'V:\alex.kwie\Script\diff17bin.ps1'"
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& 'V:\alex.kwie\Script\compareDLLs.ps1'"